'use client';
import { FormEvent, useState } from 'react'; import LogoutButton from '../logout-button'; import SwitchRoleButton from '../switch-role-button'; import DownloadButton from '../download-button'; import HistoryPanel from '../history-panel'; import MaterialsManager from '../materials-manager'; import VoiceInputButton from '../voice-input-button';
type Msg={role:'user'|'assistant';text:string};
type Target='main'|'materials20'|'materials21';
const placeholders:Record<Target,string>={main:'例：「20．審議対象資料」の見出しをハイパーリンクにして',materials20:'例：予算書へのリンクを一番上に移動して',materials21:'例：SDGsの資料へのリンクを一番上に移動して'};
export default function AdminEditor(){ const [messages,setMessages]=useState<Msg[]>([{role:'assistant',text:'修正したい内容を文章で指示してください。例：「事業目的の2段落目を、より簡潔にしてください」'}]); const [input,setInput]=useState(''); const [busy,setBusy]=useState(false); const [version,setVersion]=useState(0); const [target,setTarget]=useState<Target>('main');
async function submit(e:FormEvent){e.preventDefault();if(!input.trim()||busy)return;const instruction=input.trim();setInput('');setMessages(m=>[...m,{role:'user',text:instruction}]);setBusy(true);const res=await fetch('/api/edit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({instruction,target})});const data=await res.json() as {summary?:string;error?:string};setMessages(m=>[...m,{role:'assistant',text:data.summary||data.error||'修正できませんでした'}]);if(res.ok)setVersion(v=>v+1);setBusy(false);}
const previewSrc=target==='materials20'?`/api/materials/20?v=${version}`:target==='materials21'?`/api/materials/21?v=${version}`:`/api/document?v=${version}`;
return <main className="admin-page"><header className="topbar"><div className="brand"><h1>2026年11月事業計画書</h1><p>アカデミー｜管理者編集</p></div><div className="top-actions"><span className="status ok">● 保存は自動です</span><HistoryPanel target={target} onRestored={()=>setVersion(v=>v+1)}/><MaterialsManager target="20" label="20の資料管理" onChanged={()=>setVersion(v=>v+1)}/><MaterialsManager target="21" label="21の資料管理" onChanged={()=>setVersion(v=>v+1)}/><DownloadButton/><SwitchRoleButton label="閲覧ページ"/><LogoutButton/></div></header><div className="admin-grid"><section className="preview-pane"><iframe key={previewSrc} className="document-frame" src={previewSrc} title="編集プレビュー"/></section><aside className="chat-pane"><div className="chat-head"><div className="target-switch"><button type="button" className={target==='main'?'active':''} onClick={()=>setTarget('main')}>本文を編集</button><button type="button" className={target==='materials20'?'active':''} onClick={()=>setTarget('materials20')}>20の資料を編集</button><button type="button" className={target==='materials21'?'active':''} onClick={()=>setTarget('materials21')}>21の資料を編集</button></div></div><div className="messages">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}>{m.text}</div>)}{busy&&<div className="message assistant">文書を確認して修正しています…</div>}</div><form className="chat-form" onSubmit={submit}><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder={placeholders[target]}/><VoiceInputButton onResult={text=>setInput(prev=>(prev?prev+' ':'')+text)}/><button disabled={busy||!input.trim()}>{busy?'修正中…':'この内容で修正する'}</button></form></aside></div></main>; }
